"""create migration

Revision ID: 9e043c8627c2
Revises: dc1e94153e6c
Create Date: 2023-10-10 02:31:07.237691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e043c8627c2'
down_revision = 'dc1e94153e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('en_name', sa.String(length=32), nullable=True),
    sa.Column('zh_name', sa.String(length=32), nullable=True),
    sa.Column('short_job_desc', sa.String(length=300), nullable=True),
    sa.Column('wechat_account', sa.String(length=32), nullable=True),
    sa.Column('github_account', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=300), nullable=True),
    sa.Column('introduce', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_id'), 'info', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_info_id'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
